language: clojure
lein: 2.8.1
install:
  # Get recent node:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
before_script:
  - npm install -g eclint
  - eclint check $(git ls-files)
  - lein install
script:
  - lein test
jdk:
  - oraclejdk8
